export default {
  pages: [
    'pages/start/start',
    'pages/test/wifi',
    'pages/shop/select',
    'pages/index/index',
    'pages/notice/index',
    'pages/notice/show',
    'pages/category/category',
    'pages/goods/list',
    'pages/goods/list-vop',
    'pages/goods/fav',
    'pages/goods-details/index',
    'pages/goods-details/vop',
    'pages/shop-cart/index',
    'pages/to-pay-order/index',
    'pages/select-address/index',
    'pages/address-add/index',
    'pages/order-list/index',
    'pages/order-details/index',
    'pages/order-details/scan-result',
    'pages/order/refundApply',
    'pages/wuliu/index',
    'pages/my/index',
    'pages/withdraw/index',
    'pages/score-excharge/index',
    'pages/score-excharge/growth',
    'pages/asset/index',
    'pages/recharge/index',
    'pages/score/index',
    'pages/score/growth',
    'pages/sign/index',
    'pages/maidan/index',
    'pages/coupons/index',
    'pages/coupons/merge',
    'pages/invoice/list',
    'pages/invoice/apply',
    'pages/deposit/pay',
    'pages/live/index',
    'pages/help/detail',
    'pages/help/index',
    'pages/cms/list',
    'pages/about/index',
    'pages/idCheck/index',
    'pages/peisong/detail',
    'pages/peisong/orders',
    'pages/pwd-pay/reset',
    'pages/pwd-pay/modify',
    'pages/pwd-pay/set',
    'pages/my/feedback',
    'pages/search/index',
    'pages/my/info',
    'pages/my/setting',
    'pages/my/info-menu',
    'pages/recycle/index',
    'pages/recycle/orders',
    'pages/recycle/order-detail',
    'pages/card/logs',
    'pages/notagree/index',
    'pages/my/user-code',
  ],
  requiredPrivateInfos: ['getLocation', 'chooseAddress', 'chooseLocation'],
  subpackages: [
    {
      root: 'packageStreamMedia',
      name: 'packageStreamMedia',
      pages: [
        'pages/live-anchor/index',
        'pages/live-anchor/list',
        'pages/live-client/list',
        'pages/live-client/client',
      ],
    },
    {
      root: 'packageCps',
      name: 'packageCps',
      pages: [
        'pages/goods-details/cps-jd',
        'pages/goods-details/cps-pdd',
        'pages/goods-details/cps-taobao',
        'pages/order-list/cps',
      ],
    },
    {
      root: 'packageFx',
      name: 'packageFx',
      pages: [
        'pages/index/index',
        'pages/hehuorenfenxiao/index',
        'pages/hehuorenfenxiao/fxmember',
        'pages/apply/index',
        'pages/apply/form',
        'pages/myusers/index',
        'pages/commisionLog/index',
        'pages/report/team',
        'pages/report/city',
        'pages/myusers/myusers-detail',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '',
    navigationBarTextStyle: 'black',
    onReachBottomDistance: 50,
  },
  tabBar: {
    color: '#6e6d6b',
    selectedColor: '#e64340',
    borderStyle: 'white',
    backgroundColor: '#fff',
    list: [
      {
        pagePath: 'pages/index/index',
        iconPath: 'images/nav/home-off.png',
        selectedIconPath: 'images/nav/home-on.png',
        text: '首页',
      },
      {
        pagePath: 'pages/category/category',
        iconPath: 'images/nav/fl-off.png',
        selectedIconPath: 'images/nav/fl-on.png',
        text: '分类',
      },
      {
        pagePath: 'pages/coupons/index',
        iconPath: 'images/nav/coupon-off.png',
        selectedIconPath: 'images/nav/coupon-on.png',
        text: '优惠券',
      },
      {
        pagePath: 'pages/shop-cart/index',
        iconPath: 'images/nav/cart-off.png',
        selectedIconPath: 'images/nav/cart-on.png',
        text: '购物车',
      },
      {
        pagePath: 'pages/my/index',
        iconPath: 'images/nav/my-off.png',
        selectedIconPath: 'images/nav/my-on.png',
        text: '我的',
      },
    ],
  },
  permission: { 'scope.userLocation': { desc: '获取离你最近的门店' } },
  sitemapLocation: 'sitemap.json',
}
